#!/usr/bin/env python3
"""Build js/data.js for the wubi trainer from a Rime wubi86 dictionary file
and data/roots.json.

Source dictionary: https://github.com/rime/rime-wubi (wubi86.dict.yaml, LGPLv3).
That project compiles the standard, publicly documented 86-version Wubi
encoding rules (Wang Yongmin) into a Rime input-method dictionary; we only
reuse the resulting character/word -> code table here.

Usage:
    python3 scripts/build_data.py /path/to/wubi86.dict.yaml
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

TOP_CHARS = 3500   # single characters kept for practice, ranked by frequency
TOP_WORDS = 6000   # multi-character words/phrases kept for practice


def parse_dict(path):
    chars = {}  # char -> list of (code, weight)
    words = {}  # word -> (code, weight)
    in_data = False
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not in_data:
                if line.strip() == "...":
                    in_data = True
                continue
            if not line or line.startswith("#"):
                continue
            cols = line.split("\t")
            if len(cols) < 2:
                continue
            text, code = cols[0], cols[1]
            weight = int(cols[2]) if len(cols) >= 3 and cols[2].isdigit() else 0
            if len(text) == 1:
                chars.setdefault(text, []).append((code, weight))
            else:
                prev = words.get(text)
                if prev is None or weight > prev[1]:
                    words[text] = (code, weight)
    return chars, words


def build_char_entries(chars):
    entries = []
    for ch, variants in chars.items():
        best_weight = max(w for _, w in variants)
        codes = sorted({c for c, _ in variants}, key=len)
        full = codes[-1]
        short = codes[0]
        entries.append({
            "c": ch,
            "full": full,
            "short": short,
            "codes": codes,
            "w": best_weight,
        })
    entries.sort(key=lambda e: -e["w"])
    return entries


def build_word_entries(words):
    entries = [{"w": w, "code": code, "wt": weight} for w, (code, weight) in words.items()]
    entries.sort(key=lambda e: -e["wt"])
    return entries


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)
    dict_path = sys.argv[1]

    chars, words = parse_dict(dict_path)
    char_entries = build_char_entries(chars)[:TOP_CHARS]
    word_entries = build_word_entries(words)[:TOP_WORDS]

    roots = json.loads((ROOT / "data" / "roots.json").read_text(encoding="utf-8"))

    out = ["// Auto-generated by scripts/build_data.py — do not edit by hand.",
           "// Source: rime-wubi (https://github.com/rime/rime-wubi), LGPLv3.",
           "window.WUBI_DATA = " + json.dumps(
               {"roots": roots, "chars": char_entries, "words": word_entries},
               ensure_ascii=False, separators=(",", ":")
           ) + ";"]

    out_path = ROOT / "js" / "data.js"
    out_path.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {out_path} ({out_path.stat().st_size / 1024:.0f} KB); "
          f"{len(char_entries)} chars, {len(word_entries)} words")


if __name__ == "__main__":
    main()
